version: "3.8"

services:
  nuxt:
    build: .
    volumes:
      - ./nuxt:/nuxt:cached
      - node_modules:/src/node_modules
    working_dir: "/nuxt"
    ports:
      - "3000:3000"
      - "24678:24678"
      - "9005:9005"
    tty: true
    environment:
      - HOST=0.0.0.0
      - port=3000
      - CHOKIDAR_USEPOLLING=true

volumes:
  node_modules:
